language: node_js
sudo: enabled
before_install:
  - sudo apt-get update 
  - sudo apt-get install -y software-properties-common 
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update 
  - sudo apt-get install -y ansible

install:
  - ansible-playbook playbook.yml --connection=local --inventory-file test-inventory

script:
  - echo "Success"
