---
- name: install mysql and create db
  hosts: all
  environment:
    TEST: "{{ UPass }}"
  #vars:
  #  PASS="TestPassword123"
  tasks:
  - name: debug stuff
    shell: printenv
    register: debug
  - debug:
      var: debug
  - name: debug stuff2
    shell: echo hello
    register: debug2
  - debug:
      var: debug2

  - name: update sources
    shell: apt-get update
  
  - name: install mysql
    shell: apt-get install -y mysql-server mysql-client
  
  - name: start mysql
    shell: /etc/init.d/mysql restart 
  
  - name: set credentials
    shell: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$RPass';"

  - name: create db
    shell: mysql -e "CREATE DATABASE IF NOT EXISTS $DB_Name;"

  - name: add user to manage create db
    shell: mysql -e "CREATE USER 'sean'@'localhost' IDENTIFIED BY '$UPass';"

  - name: grant user privileges to access db
    shell: mysql -e "GRANT ALL PRIVILEGES ON $DB_Name.* TO 'sean'@'localhost'; FLUSH PRIVILEGES;"
